version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
