version: '3.8'

services:
  publisher:
    image: bigdatainf/publisher
    working_dir: /app
    command: python -u script.py
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password

  consumer:
    image: bigdatainf/consumer
    working_dir: /app
    command: python -u script.py
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
